### PR TITLE
Game logic with class

### PR DESCRIPTION
**Pull request by flpfar**
This branch adds the logic of the game inside the class Board, which contains the methods:
- initialize getting the users and creating the board
- show_board returning a string with a presentable board
- register_move to validate the user inputs and insert into board
- checker to verify if the game is over and who was the winner

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @flpfar, @FrancoRosa. :clap:**
**You have done a nice work :+1:, the behavior of  your app is in order. But we need to make a little change to the implementation :fast_forward:**

- You need to create an additional class in this project. It cannot be completed with only one class. I suggest you create a player class and use instances of the class in your game.



- It is a ruby convention to use **'require_relative'** to import files in your directory instead of **'require'**.

**Optional Suggestions:**
- You can refactor your checker method to take a player or player_symbol argument and check win for only that player. It can then be called with the current_player as argument during game play. This will make the checker method more DRY.

- It is better to represent empty state on the board with 'nil'.

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by flpfar** [comment]
Thank you for reviewing our code, @mosesogwo ! 
We implemented the suggestions and made some changes:
- Instead of creating a player class, we created a BoardChecker and a BoardFormatter.
- We are now initializing the board with the positions (from 1 to 9) instead of empty spaces.

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great work, Congratulation :+1: Project Approved.
You made changes required previously. Go ahead and merge to develop.

_Goodluck in your next milestone_ *Happy coding*

**Pull request merged**
